config/routes.rb
Rails.application.routes.draw do
  root 'home_page#index'

  get    'student_search', to: 'home_page#student_search'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get    '/logout',  to: 'sessions#destroy'

  get '/students/search',  to: 'students#search'

  get     '/packages/in',        to: 'packages#new'
  post    '/packages/in',        to: 'packages#create'
  get     '/packages/out',       to: 'packages#edit'
  post    '/packages/out',       to: 'packages#update'
  get     '/packages/find',      to: 'packages#find'

  get     '/reservations',        to: 'reservations#index'
  get     '/reservations/find',   to: 'reservations#find'
  post    '/reservations/new',    to: 'reservations#create'
  post    '/reservations/update', to: 'reservations#update'
  delete  '/reservations/delete', to: 'reservations#destroy'
  
  get     '/keys',                to: 'spare_keys#index'
  get     '/keys/find',           to: 'spare_keys#find'
  post    '/keys/update',         to: 'spare_keys#update'
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :student
  before_create :set_defaults

  private
  def set_defaults
    self.checked_in ||= false
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :confirm_signed_in

  def index
  end

  def find
    room = Room.find_by(building: params[:building], number: params[:room])

    if !room.nil?
      reservations = Reservation.where(room_id: room.id).all.as_json
      reservations.map do |r|
        student = Student.find(r["student_id"])
        r["lname"] = student.lname
        r["bannerID"] = student.bannerID
      end

      render json: { room_exists: true, reservations: reservations }
    else
      render json: { room_exists: false }
    end
  end

  def create
    room = Room.find_by(building: params[:building], number: params[:room])
    student_id = Student.find_by(bannerID: params[:bannerID]).id
    start_date = DateTime.parse params[:start]
    end_date = DateTime.parse params[:end]

    Reservation.create(start_date: start_date, end_date: end_date, room_id: room.id, student_id: student_id)
    render json: { success: true }
  end

  # Update checkin status
  def update
    id = params[:id]
    reservation = Reservation.find(id)
    reservation.update(checked_in: params[:checked_in])

    render json: { success: true }
  end

  def destroy
    id = params[:reservation_id]
    reservation = Reservation.find(id)

    if !reservation.nil?
      reservation.destroy
      render json: { success: true }
    else
      render json: { success: false }
    end
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_with(model: reservation, local: true) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date, id: :reservation_start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.datetime_select :end_date, id: :reservation_end_date %>
  </div>

  <div class="field">
    <%= form.label :recurring %>
    <%= form.check_box :recurring, id: :reservation_recurring %>
  </div>

  <div class="field">
    <%= form.label :room_id %>
    <%= form.number_field :room_id, id: :reservation_room_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<% content_for :title do %>
  Reservations
<% end %>

<% content_for :body do %>
  <div>
    <div class='input-with-label'>
      <label>Residence Hall</label>
      <select name="hall" v-model='selectedHall' class='search-box'>
        <option v-for='hall in residenceHalls'>
              {{ hall }}
        </option>
      </select>
    </div>

    <div class='input-with-label'>
      <label>Room #</label>
      <input type='text' maxlength='3' size='3' class='search-box' v-model='selectedRoom'>
    </div>

    <input type="submit" value="Search" class='btn btn-primary' v-on:click='submitSearch'>

    <div v-if='searchSent && reservations.length > 0'>
      <h2>Reservations for this room</h2>
      <table class='table' >
        <tr>
          <th>Student Last Name</th>
          <th>BannerID</th>
          <th>From</th>
          <th>Until</th>
        </tr>
        <tr v-for="(r, i) in reservations">
          <td>{{ r.lname }}</td>
          <td>{{ r.bannerID }}</td>
          <td>{{ formatDate(r.start_date) }}</td>
          <td>{{ formatDate(r.end_date) }}</td>
          <td>
            <button class='btn btn-primary' @click='deleteReservation(r)'>Cancel</button>
          </td>
          <td>
            <button v-if='!r.checked_in'
                    class='btn btn-primary'
                    @click='updateReservation(r, true)'>Checkin</button>
            <button v-else
                    class='btn btn-primary'
                    @click='deleteReservation(r)'>Checkout</button>
          </td>
        </tr>
      </table>
    </div>
    <div v-else>
      <h5 v-if='searchSent'>There are currently no reservations for this room.</h5>
    </div>

    <br><br><br><br><br><br>

    <div v-if='searchSent'>
      <h3>Create a new reservation</h3>

      <div class='input-with-label'>
        <label>Start Date</label>
        <input type='text' id='start-date' class='datepicker'>
      </div>
      
      <div class='input-with-label'>
        <label>End Date</label>
        <input type='text' id='end-date' class='datepicker'>
      </div>

      <div class='input-with-label'>
        <label>BannerID</label>
        <input type='text' v-model='bannerID'>
      </div>

      <input type="submit" value="Create Reservation" class='btn btn-primary' v-on:click='createReservation'>
    </div>

    <div v-if='reservationCreated'>
      <p>Reservation created successfully.</p>
    </div>
  </div>

  <%= link_to 'Back', root_path %>
  <%= javascript_include_tag 'reservations' %>
<% end %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @reservation.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @reservation.end_date %>
</p>

<p>
  <strong>Recurring:</strong>
  <%= @reservation.recurring %>
</p>

<p>
  <strong>Room:</strong>
  <%= @reservation.room_id %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>