config/routes.rb
Rails.application.routes.draw do
  root 'home_page#index'

  get    'student_search', to: 'home_page#student_search'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get    '/logout',  to: 'sessions#destroy'

  get '/students/search',  to: 'students#search'

  get     '/packages/in',        to: 'packages#new'
  post    '/packages/in',        to: 'packages#create'
  get     '/packages/out',       to: 'packages#edit'
  post    '/packages/out',       to: 'packages#update'
  get     '/packages/find',      to: 'packages#find'

  get     '/reservations',        to: 'reservations#index'
  get     '/reservations/find',   to: 'reservations#find'
  post    '/reservations/new',    to: 'reservations#create'
  post    '/reservations/update', to: 'reservations#update'
  delete  '/reservations/delete', to: 'reservations#destroy'
  
  get     '/keys',                to: 'spare_keys#index'
  get     '/keys/find',           to: 'spare_keys#find'
  post    '/keys/update',         to: 'spare_keys#update'
end

app/models/spare_key.rb
class SpareKey < ApplicationRecord
  before_create :set_defaults

  private
  def set_defaults
    self.checked_out ||= false
  end
end

app/controllers/spare_keys_controller.rb
class SpareKeysController < ApplicationController
  before_action :confirm_signed_in

  def index
  end

  def find
    room = Room.find_by(building: params[:building], number: params[:room])

    if !room.nil?
      keys = SpareKey.where(room_id: room.id).all.as_json

      keys.map do |k|
        unless k['student_id'].nil?
          student = Student.find(k['student_id'])
          k['fname'] = student.fname
          k['lname'] = student.lname
        end
      end

      render json: { room_exists: true, keys: keys }
    else
      render json: { room_exists: false }
    end
  end

  def update
    key = SpareKey.find(params[:key_id])
    student = Student.find_by(bannerID: params[:bannerID])
    student_id = nil

    unless student.nil?
      student_id = student.id
    end

    key.update(checked_out: params[:checkout_status], student_id: student_id)
    render json: { success: true }
  end
end

app/helpers/spare_keys_helper.rb
module SpareKeysHelper
end

app/views/spare_keys/_form.html.erb
<%= form_with(model: spare_key, local: true) do |form| %>
  <% if spare_key.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(spare_key.errors.count, "error") %> prohibited this spare_key from being saved:</h2>

      <ul>
      <% spare_key.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :barcode %>
    <%= form.text_field :barcode, id: :spare_key_barcode %>
  </div>

  <div class="field">
    <%= form.label :keycode %>
    <%= form.text_field :keycode, id: :spare_key_keycode %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/spare_keys/edit.html.erb
<h1>Editing Spare Key</h1>

<%= render 'form', spare_key: @spare_key %>

<%= link_to 'Show', @spare_key %> |
<%= link_to 'Back', spare_keys_path %>

app/views/spare_keys/index.html.erb
<% content_for :title do %>
  Key Checkin/Checkout
<% end %>

<% content_for :body do %>
  <div>
    <div class='input-with-label'>
      <label>Residence Hall</label>
      <select name="hall" v-model='selectedHall' class='search-box'>
        <option v-for='hall in residenceHalls'>
              {{ hall }}
        </option>
      </select>
    </div>

    <div class='input-with-label'>
      <label>Room #</label>
      <input type='text' maxlength='3' size='3' v-model='selectedRoom' class='search-box'>
    </div>

    <input type="submit" value="Search" class='btn' v-on:click='findKeys'>

    <div v-if='keys.length > 0'>
      <h2>Reservations for this room</h2>
      <table class='table' >
        <tr>
          <th>Key #</th>
          <th>Checkout status</th>
        </tr>
        <tr v-for="key in keys">
          <td>{{ key.id }}</td>
          <td>{{ formatCheckoutStatus(key) }}</td>

          <td v-if='key.checked_out'>
            <button v-on:click='checkin(key)' class='btn'>Check key in</button>
          </td>
          
          <td v-else>
            <key-checkout v-bind:key-ref='key' v-on:checkout="checkout">
          </td>
        </tr>
      </table>
    </div>

  </div>

  <%= link_to 'Back', root_path %>
  <%= javascript_include_tag 'key_checkout' %>
  <%= javascript_include_tag 'spare_keys' %>
<% end %>

app/views/spare_keys/new.html.erb
<h1>New Spare Key</h1>

<%= render 'form', spare_key: @spare_key %>

<%= link_to 'Back', spare_keys_path %>

app/views/spare_keys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Barcode:</strong>
  <%= @spare_key.barcode %>
</p>

<p>
  <strong>Keycode:</strong>
  <%= @spare_key.keycode %>
</p>

<%= link_to 'Edit', edit_spare_key_path(@spare_key) %> |
<%= link_to 'Back', spare_keys_path %>